# Generated by Django 6.1.1 on 2026-09-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_produtos_imagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
    ]
